[[TestCases]]
  RunCmd = "{{ $.LoomPath }} dpos3 list-validators"
  Condition = "excludes"
  Excluded = ["Error"]

# This just creates a pending action... that never seems to get applied for some reason
#[[TestCases]]
#  RunCmd = "{{ $.LoomPath }} chain-cfg set-setting AppStore.CloneStateAtHeight --value 20 --build 0 -k {{index $.NodePrivKeyPathList 0}}"
#  Condition = "excludes"
#  Excluded = ["Error", "RPC error"]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg config"
  Condition = "excludes"
  Excluded = ["Error", "RPC error"]

# wait 310s (~5m) for 2 new blocks to be generated (310000ms)
[[TestCases]]
  RunCmd = "wait_for_block_height_to_reach 0 17"

[[TestCases]]
  RunCmd = "kill_and_restart_node 1 1"

# wait for node 1 to catch up
[[TestCases]]
  RunCmd = "wait_for_node_to_catch_up 1"

[[TestCases]]
  Delay = 10000
  RunCmd = "{{ $.LoomPath }} dpos3 downtime-record"
  Condition = "excludes"
  Excluded = ["Error", "RPC error"]
