[[TestCases]]
  RunCmd = "loom chain-cfg list-features"
  Condition = "contains"
  Expected = ['featureInfos']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature hardfork -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature hardfork -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['not authorized']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature hardfork -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['not authorized']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature hardfork -k {{index $.NodePrivKeyPathList 3}}"
  Condition = "contains"
  Expected = ['not authorized']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature hardfork -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['feature already exists']
 
[[TestCases]]
  RunCmd = "loom chain-cfg enable-feature hardfork -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom chain-cfg enable-feature hardfork -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom chain-cfg get-feature hardfork -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['50','PENDING']

[[TestCases]]
  RunCmd = "loom chain-cfg enable-feature hardfork -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom chain-cfg get-feature hardfork -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['75', 'WAITING']

[[TestCases]]
  RunCmd = "loom chain-cfg add-feature newfeature -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = []

[[TestCases]]
  RunCmd = "loom chain-cfg list-features -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['hardfork','newfeature']

[[TestCases]]
  RunCmd = "loom chain-cfg get-feature hardfork -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['75', 'ENABLED']


