[[TestCases]]
  RunCmd = "check_validators"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = ""

[[TestCases]]
  RunCmd = "kill_and_restart_node 10 1"

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  All = true

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1250000 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 1}} 100 -k {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1250000 -k {{index $.NodePrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 2}} 100 --name numero_dos -k {{index $.NodePrivKeyPathList 2}}"

[[TestCases]]
  RunCmd = "example-cli call list_candidatesV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 1}}", "{{index $.NodePubKeyList 2}}"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = ""
  All = true
