[[TestCases]]
  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
  Condition = "contains"
  Expected = ["Value"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 1}} 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.AccountAddressList 1}} -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ["2000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["8000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance dposV2"
  Condition = "contains"
  Expected = ["2000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call unbondV2 {{index $.AccountAddressList 1}} 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["10000000000000000000"]
