[[TestCases]]
  RunCmd = "check_validators"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = ""

[[TestCases]]
  RunCmd = "kill_and_restart_node 10 1"

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Node = 1
  Condition = "contians"
  Expected = ["Error"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Node = 0
  Condition = "contians"
  Expected = ["Value"]

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1250000 -k {{index $.NodePrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 2}} 100 --name numero_dos -k {{index $.NodePrivKeyPathList 2}}"

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1250000 -k {{index $.NodePrivKeyPathList 3}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 3}} 100 -k {{index $.NodePrivKeyPathList 3}}"

[[TestCases]]
  RunCmd = "example-cli call list_candidatesV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 3}}", "{{index $.NodePubKeyList 2}}"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Node = 0
  Condition = "contians"
  Expected = ["Value"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Node = 1
  Condition = "contians"
  Expected = ["Value"]

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1250000 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 1}} 100 -k {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 200000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 2}} 200000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 200000 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 3}} 200000 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "kill_and_restart_node 100 1"

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 1}}", "{{index $.NodePubKeyList 2}}", "{{index $.NodePubKeyList 3}}"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Node = 1
  Condition = "contians"
  Expected = ["Error"]

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 200000 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 3}} 200000 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.NodeAddressList 2}} {{index $.AccountPrivKeyPathList 0}}"
# Condition = "contains"
# Expected = ["2000000000000000000"]
