[[TestCases]]
  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
  Condition = "contains"
  Expected = ["Value"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 10 -p {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 20 -p {{index $.AccountPrivKeyPathList 3}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 1}} -p {{index $.AccountPrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 2}} -p {{index $.AccountPrivKeyPathList 2}}"

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 3}} -p {{index $.AccountPrivKeyPathList 3}}"

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 1}} 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 2}} 20 -p {{index $.AccountPrivKeyPathList 3}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 3}} 10 -p {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call elect_delegationV2 -p {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.AccountAddressList 2}} -p {{index $.AccountPrivKeyPathList 3}}"
  Condition = "contains"
  Expected = ["2000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.AccountAddressList 1}} -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ["2000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.AccountAddressList 3}} -p {{index $.AccountPrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ["1000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
# TODO make this check for the right addresses, too Expected = ["\"power\": \"20000000000\""]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["8000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance dposV2"
  Condition = "contains"
  Expected = ["5000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call unbondV2 {{index $.AccountAddressList 1}} 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["10000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call elect_delegationV2 -p {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
# TODO make this check for the right addresses, too
  Expected = ["\"power\": \"10000000000\""]
