[[TestCases]]
  RunCmd = "/usr/bin/curl -X POST --data {\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83} $LOOM_NODE_URI/eth"
  All = true
  Condition = "contains"
  Expected = [
                "\"result\": \"0x",
                "\"jsonrpc\": \"2.0\",",
                "\"id\": 83"
             ]
