[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} coin approve user-deployer-whitelist 10000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} userdeployer add {{index $.AccountAddressList 1}} default -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} userdeployer add {{index $.AccountAddressList 1}} default -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['deployer already exists']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} userdeployer add {{index $.AccountAddressList 1}} tierId -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['Please specify tierId <default>']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} userdeployer getdeployers {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ['default:{{index $.AccountAddressList 1}}','"Flags": "EVM"']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} userdeployer getContracts {{index $.AccountAddressList 1}} -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

#Checks whitelisting fees is debited from user after adding dpeloyer
 [[TestCases]]
   Dir = ""
   RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 0}}"
   Condition = "contains"
   Expected = ["99999999999999999999999990"]
   Delay = 500

