# Loom Node config file
# See https://loomx.io/developers/docs/en/loom-yaml.html for additional info.
# 
# Cluster-wide settings that must not change after cluster is initialized.
#
# Cluster ID
ChainID: ""
RegistryVersion: 1
ReceiptsVersion: 1
EVMPersistentTxReceiptsMax: 2000
EVMAccountsEnabled: false
DPOSVersion: 1
BootLegacyDPoS: false
CreateEmptyBlocks: true
#
# Network
#
RPCListenAddress: "tcp://127.0.0.1:46657"
RPCProxyPort: 46658
RPCBindAddress: "tcp://0.0.0.0:46658"
Peers: ""
PersistentPeers: ""
#
# Throttle
#
Oracle: "default:0xAfaA41C81A316111fB0A4644B7a276c26bEA2C9F"
DeployEnabled: true
CallEnabled: true
SessionDuration: 600
Karma:
  Enabled: true
  ContractEnabled: false
  UpkeepEnabled: true
  MaxCallCount: 10
  SessionDuration: 60
GoContractDeployerWhitelist:
  Enabled: true
  DeployerAddressList:
    - "0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
    - "0x40352F3aeD8E7281795dEf0CA7581F41DbE41F5B"
    - "0x2Ff9aB3aBDbC79efD22e3AC79787d8f9B5F99B40"
TxLimiter:
  LimitDeploys: true
  LimitCalls: true
  CallSessionDuration: 3
  DeployerAddressList:
  - "default:0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
  - "default:0x40352F3aeD8E7281795dEf0CA7581F41DbE41F5B"
  - "default:0x2Ff9aB3aBDbC79efD22e3AC79787d8f9B5F99B40"
#
# Logging
#
LogDestination: ""
ContractLogLevel: ""
LoomLogLevel: ""
BlockchainLogLevel: "error"
LogStateDB: false
LogEthDbBatch: false
Metrics:
  EventHandling: true
#
# Transfer Gateway
#
TransferGateway:
  # Enables the Transfer Gateway Go contract on the node, must be the same on all nodes.
  ContractEnabled: false
  # Enables the in-process Transfer Gateway Oracle.
  # If this is enabled ContractEnabled must be set to true.
  OracleEnabled: false
  # URI of Ethereum node the Oracle should connect to, and retrieve Mainnet events from.
  EthereumURI: "ws://127.0.0.1:8545"
  # Address of Transfer Gateway contract on Mainnet
  # e.g. 0x3599a0abda08069e8e66544a2860e628c5dc1190
  MainnetContractHexAddress: ""
  # Path to Ethereum private key on disk that should be used by the Oracle to sign withdrawals,
  # can be a relative, or absolute path
  MainnetPrivateKeyPath: ""
  # Path to DAppChain private key on disk that should be used by the Oracle to sign txs send to
  # the DAppChain Transfer Gateway contract
  DAppChainPrivateKeyPath: ""
  DAppChainReadURI: "http://127.0.0.1:46658/query"
  DAppChainWriteURI: "http://127.0.0.1:46658/rpc"
  # Websocket URI that should be used to subscribe to DAppChain events (only used for tests)
  DAppChainEventsURI: "ws://127.0.0.1:46658/queryws"
  DAppChainPollInterval: 10
  MainnetPollInterval: 10
  # Oracle log verbosity (debug, info, error, etc.)
  OracleLogLevel: "info"
  OracleLogDestination: "file://tgoracle.log"
  # Number of seconds to wait before starting the Oracle.
  OracleStartupDelay: 5
  # Number of seconds to wait between reconnection attempts.
  OracleReconnectInterval: 0
  # Address on from which the out-of-process Oracle should expose the status & metrics endpoints.
  OracleQueryAddress: "127.0.0.1:9998"
#
# Plasma Cash
#
PlasmaCash:
  ContractEnabled: false
  OracleEnabled: false
#
# Block store
#
BlockStore:
  # None | LRU | 2Q
  CacheAlgorithm: None
  CacheSize: 10000

#
# Cashing store 
#
CachingStoreConfig: 
  CachingEnabled: true
  # Number of cache shards, value must be a power of two
  Shards: 1024 
  # Time after we need to evict the key
  EvictionTimeInSeconds: 3600 
  # interval at which clean up of expired keys will occur
  CleaningIntervalInSeconds: 10 
  # Total size of cache would be: MaxKeys*MaxSizeOfValueInBytes
  MaxKeys: 50000 
  MaxSizeOfValueInBytes: 2048 
  # Logs operations
  Verbose: true 
  LogLevel: "info" 
  LogDestination: "file://-" 
#
# Hsm 
#
HsmConfig:
  # flag to enable HSM
  HsmEnabled: false
  # device type of HSM
  HsmDevType: "yubihsm"
  # the path of PKCS#11 library
  HsmP11LibPath: ""
  # connection URL to YubiHSM
  HsmConnURL: localhost:12345
  # Auth key ID for YubiHSM
  HsmAuthKeyID: 1
  # Auth password
  HsmAuthPassword: "password"
  # Sign Key ID for YubiHSM
  HsmSignKeyID: 0
  # key domain
  HsmSignKeyDomain: 1
#
# Oracle serializable 
#
DPOSv2OracleConfig:
  Enabled: false
  StatusServiceAddress: "0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
  MainnetPollInterval: 1



#
# App store
#
AppStore:
  # If true the app store will be compacted before it's loaded to reclaim disk space.
  CompactOnLoad: false
  # Maximum number of app store versions to keep, if zero old versions will never be deleted.
  MaxVersions: 0
  # Number of seconds to wait after pruning a batch of old versions from the app store.
  # If this is set to zero the app store will only be pruned after a new version is saved.
  PruneInterval: 0
  # Number of versions to prune at a time.
  PruneBatchSize: 50
# These should pretty much never be changed
RootDir: ""
DBName: ""
GenesisFile: ""
PluginsDir: ""
#
# Here be dragons, don't change the defaults unless you know what you're doing
#
EVMDebugEnabled: false

#
# EventStore
#
EventStore:
  DBName: event
  DBBackend: goleveldb

#
# EventDispatcher
#
EventDispatcher:
  # Available dispatcher: "db_indexer" | "log" | "redis"
  Dispatcher: log
  
